"""Add staff and login_detail models

Revision ID: 566b9c1f371a
Revises: 
Create Date: 2024-08-13 21:39:32.341382

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '566b9c1f371a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('staff',
    sa.Column('staff_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=255), nullable=False),
    sa.Column('mobile_number', sa.String(length=15), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_date', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('updated_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['dev.staff.staff_id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['dev.staff.staff_id'], ),
    sa.PrimaryKeyConstraint('staff_id'),
    sa.UniqueConstraint('email'),
    schema='dev'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('staff', schema='dev')
    # ### end Alembic commands ###
